### ISSUE TITLE
Expand Series Functionality

### ISSUE THREAD

**Issue by josephting** [luizdepra/hugo-coder#150]
I would like to work on this feature but I have some questions.

Since `series` is an array, posts can be in multiple series.

1. How should we go about listing related posts with it?
    - Use first series only?
    - Use all with the first series taking priority?
2. How many related posts should be listed under **See Also** section?
3. Should we make the number of related posts configurable?

## Todo

- [x] Create a See also section at the end of posts and pages.
- [x] Check if the series list pages are ok. And make changes if necessary.
- [x] Translate series to Portuguese. (Hint: It is séries).

_Originally posted by @luizdepra in https://github.com/luizdepra/hugo-coder/pull/147#issuecomment-469277019_

**Comment by luizdepra** [comment]
Let's see...

1. I would go for showing related post s from all series, following the array order. Maybe something like this:
```
series = ["WASM Tutorial", "Go for the Web"]
...
See also in WASM Tutorial:
  - WASM Intro
  - Advanced WASM

See also in Go for the Web:
  - Your first Go API
  - Front-end development with Go
  - Go and Elm
```

2. and 3. I think 5 posts is a good default quantity, but we should make it configurable.
