### ISSUE TITLE
[v2 - Roadmap] Planned Changes and Features 

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#51]
This issue purpose is to guide the development of the version 2 of Hugo Coder. Here is a list of planned changes and new features.
New ideas and contributions are welcome.

- [ ] Replace LESS with SCSS (after Hugo v0.43 - [SCSS pipeline](https://github.com/gohugoio/hugo/commit/dea71670c059ab4d5a42bd22503f18c087dd22d4))
- [ ] Template refactor
- [ ] Inverted Color style - partially done at #34
- [ ] Better support for Custom Code Highlight
- [ ] Mobile Collapsible Menu
- [ ] Tags and Categories Taxonomy
- [ ] Series Taxonomy
- [ ] Projects Archetype
- [ ] Talks/Presentations Archetype - partially done at #12
- [ ] Different fonts for text and titles
- [ ] Customizable Fonts
- [x] Author Avatar - #41
- [ ] I18N support

**Comment by khos2ow** [comment]
- I've done i8n already in my own fork, I will be able to open a PR for that.
- also done some part of taxonomy, I can finish that up too.
- +1 on fonts.
- also wanted to suggest to make code highlight customizable. although I liked the current white on black, but I ended up changing that with a 4 colors on lightgray for my own.

**Comment by luizdepra** [comment]
Good idea!

**Comment by Reijnn** [comment]
Really looking forward to this! I hope I can help out at some point since I'm not that efficient with Hugo to help build just yet.

**Comment by rdhox** [comment]
Look very good. I'm busy on a project, but I will try to see for the Mobile Collapsible Menu. If I have the time to code something worth it, I will open PR. I like the tilt I must say, I will try to keep the idea!

**Comment by luizdepra** [comment]
I'll try to put every item of the list in a separated issue and describe all planned changes.

**Comment by luizdepra** [comment]
I openned one issue for each improvement. Also created a milestone.
There is no need to keep this issue open.
